### ISSUE TITLE
Error in (forced, unneeded) redirections

### ISSUE THREAD

**Issue by polettix** [bluefeet/GitLab-API-v3#32] opened 2017-10-22 00:08 UTC
I tried using this module with the "main" GitLab instance at [gitlab.com](http://gitlab.com) but without success. It eventually boils down to `Role::REST::Client` *not* following redirections, although the need for redirection is actually caused by the following line:

https://github.com/bluefeet/GitLab-API-v3/blob/d72617e208939cedb680da4d49995788c4ce6977/lib/GitLab/API/v3/RESTClient.pm#L51

It adds an arbitrary leading slash character `/` even when the passed path contains one, resulting in URIs like this:

    https://gitlab.com/api/v3//projects/XXXXXXX/issues 

The remote server chokes at the double slash between `v3` and `projects`, and sends a permanent redirection 308 towards the cleaned up URI:

    https://gitlab.com/api/v3/projects/XXXXXXX/issues 

While I think that `Role::REST::Client` should handle redirections better, I guess it's easy on this side to just avoid triggering the problem.

I also wonder how can this possibly work for anyone else... maybe I'm doing something wrong?

**Comment by bluefeet** [comment] 2017-11-30 23:47
What is the value of your `url` argument?  I'm guessing it ends in a slash?  The code assumes that it does not, I can add some trimming logic to it so it "just works".

**Comment by bluefeet** [comment] 2017-12-09 18:51
I won't be fixing this in the v3 module, but I would still like your feedback.  Once you confirm (or not) that the issue is just a trailing `/` in your `url` argument then I'll go ahead and make a fix in the v4 module at:
https://github.com/bluefeet/GitLab-API-v4

**Comment by polettix** [comment] 2017-12-09 20:31
Sorry, I prepared an answer but forgot to post it.

The bottom line is that the issue is not in what `url` is passed, it's in `GitLab::API::v3`:

- one slash is added by the methods that wrap REST calls, e.g. [sub issues](https://github.com/bluefeet/GitLab-API-v3/blob/master/lib/GitLab/API/v3.pm#L1594) has this (note the slash before `projects`):

      my $path = sprintf('/projects/%s/issues', (map { uri_escape($_) } @_));
      return $self->get( $path, ( defined($params) ? $params : () ) );

- the following call to the HTTP method (`get` in the example above) is [`around`ed](https://github.com/bluefeet/GitLab-API-v3/blob/master/lib/GitLab/API/v3/RESTClient.pm#L42) and [adds another slash](https://github.com/bluefeet/GitLab-API-v3/blob/master/lib/GitLab/API/v3/RESTClient.pm#L51) before calling the original method:

      $res = $self->$orig( "/$path", @_ );

Hence, even with a *trailing-slash-free* `url` parameter you're always going to get two slashes in the call. This is why I'm a bit surprised to be the first to hit this issue!

**Closed** 2017-12-16 00:01 UTC

**Comment by bluefeet** [comment] 2017-12-16 00:02
Thank you!  I'll port this patch to bluefeet/GitLab-API-v4 as well.

**Comment by bluefeet** [comment] 2017-12-16 00:09
And I'll go ahead and put out a release of v3 for this as well.
